sudo: required
services:
  - docker
  
before_install:
  - docker build -t  frankfoti/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true frankfoti/react-test npm test
  
after_success:
  - docker build -t frankfoti/multi-client ./client
  - docker build -t frankfoti/multi-nginx ./nginx
  - docker build -t frankfoti/multi-server ./server
  - docker build -t frankfoti/multi-worker ./worker